---
title: "Assignment9"
author: "Yifei"
date: "2018/10/24"
output: html_document
---
```{r}
#1  Load the full data file into R and then extract the proper columns. After that, deal with missing values.

library(stringr)
library(zoo)
library(xts)
library(dplyr)
library(RSQLite)
library(Hmisc)
bs <- read.csv("Bird Strikes.csv")
newBr <- bs %>%
select(Aircraft..Type , Airport..Name,Effect..Impact.to.flight,FlightDate,Record.ID,Aircraft..Airline.Operator,Origin.State,Feet.above.ground,Altitude.bin)
```



```{r}
newBr <- newBr %>%
  rename(AircraftType = Aircraft..Type) %>%
  rename(DepAirport = Airport..Name) %>%
  rename(Impact = Effect..Impact.to.flight) %>%
  rename(Date = FlightDate) %>%
  rename(ID = Record.ID) %>%
  rename(Airline = Aircraft..Airline.Operator) %>%
  rename(OriginState = Origin.State) %>%
  rename(Ft = Feet.above.ground) %>%
  rename(Altitude = Altitude.bin) 

newBr$AircraftType <- as.character(newBr$AircraftType)  
newBr$DepAirport <- as.character(newBr$DepAirport)  
newBr$Impact <- as.character(newBr$Impact) 
newBr$Date <- as.character(newBr$Date) 
newBr$ID <- as.character(newBr$ID) 
newBr$Airline <- as.character(newBr$Airline) 
newBr$OriginState <- as.character(newBr$OriginState) 
newBr$Ft <- as.character(newBr$Ft) 
newBr$Ft <- str_remove(newBr$Ft,",")
newBr$Ft <- as.numeric(newBr$Ft) 
newBr$Altitude <- as.character(newBr$Altitude) 
newBr$AircraftType[newBr$AircraftType == ""] <- "Empty"
newBr$Impact[newBr$Impact ==''] <- "None"

newBr$Ft[which(is.na(newBr$Ft))] <- mean(na.omit(newBr$Ft))

```

```{r}
#2 Perform a min-max normalization (definition) on the 'Feet Above Ground' field and place the value into the field Altitude.
min <- min(newBr$Ft)
max <- max(newBr$Ft)

newBr$Altitude <-(newBr$Ft - min)/(max-min)
```

```{r}
#3 Save the new data frame to a CSV file.
#delete the time
newBr$Date <- str_remove(newBr$Date,"0:00")
newBr$Date <- as.Date(newBr$Date,"%m/%d/%Y")
write.csv(newBr, file = "Bird_Strike_Update.csv")
```


