```{r}
#Task 1
# Load the XML document at the URL  above directly into a data frame
library(XML)
library(dplyr)
library(ggplot2)
source <- xmlToDataFrame("http://ds4100-f18.weebly.com/uploads/8/6/5/9/8659576/senators.xml")

options(repos="https://cran.rstudio.com" )

```

```{r}
#Task 2
# function senatorsFrom() that returns the names of the senators for a given state, i.e., the function takes a state as an argument and returns the names of the senators for that state in a vector.
# the input is the name of the state
senatorsFrom <- function(State){
 Senatorsform <- source %>%
   filter(state == State) %>%
   mutate(FullName = paste(first_name, last_name, sep = " ")) %>%
  select(FullName)
 output<- as.vector(Senatorsform$FullName)
 return(output)
}
```

```{r}
#Task 3
# function senatorCountByParty() returns the the number of senators for each party.
senatorCountByParty <- function(){
  SenatorParty <- source %>%
    group_by(party) %>%
    summarise(numberOfSenator = n())
  return(SenatorParty)
}
```

```{r}
#Task 4
# function listSenators() that displays all the senators sorted by last name, their party in parenthesis after their name, their state, and their phone number, e.g., John Kerry (D) - MA (202) 224-2742

listSenators <- function(){
  senatorList <- source %>%
    arrange(last_name, party, state, phone) %>%
    mutate(inFormat = paste0(first_name, " ",last_name, " (", party, ") - ", state, " ", phone)) %>%
    select(inFormat)
  
  return(senatorList)
}
```
