```{r}

library(bitops)
library(XML)
library(methods)
library(RCurl)
library(dplyr)

#1 Load and then parse the XML document at the URL
url <- "http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/data/auctions/ebay.xml"

ebayhtml <- xmlTreeParse(url)
ebay <- xmlRoot(ebayhtml)

# the number of auctions more than x,
# the number x is an input number
bidsLargerThan <- function(x){
 counter <- 0
 for(i in 1:xmlSize(ebay)){
   ifelse(xmlValue(ebay[[i]][[5]][[5]])>x, counter <- counter+1, counter)
 }
 return(counter)
}

```

```{r}
#2
input <-xmlToDataFrame("getHistory15.xml")
#xData <-getURL(fileURL)
#doc <-xmlParse(fileURL)
#security <-xmlRoot("getHistory15.xml")
# 1.  the highest closing price for the security
highestClosing <- function(){
 output1 <- max(input$close, na.rm = TRUE)
  return(output1)
}

# 2. the total volume traded
totalVolume <- function(){
  k <- as.numeric(input$volume)
  output2 <- sum(k, na.rm = TRUE)
  return(output2)
}

# 3. the average trading volume during each TWO HOUR block of the trading day
AverageVolume <- function(){


  output <- input %>%
    filter(between(row_number(), 2, n())) %>%
     select(timestamp, volume) %>%
     rbind(c("2013-10-29T15:15:00-05:00", 0)) %>%
     rbind(c("2013-10-29T16:15:00-05:00", 0)) %>%
     rbind(c("2013-10-29T16:30:00-05:00", 0)) %>%
     rbind(c("2013-10-29T16:45:00-05:00", 0)) %>%
     mutate(sum = 0) %>%
     arrange(timestamp) 
     
  #I am having trouble to trasfer volume from character to numeric, if i can do that i would use for loop to sum each 8 period and divide by 2 to make the table.
  return(output)
}


#15:15 16:15 16:30 16:45
```
